apiVersion: apm.k8s.elastic.co/v1alpha1
kind: ApmServer
metadata:
  name: apm-server
  namespace: textsearch
spec:
  version: 7.2.0
  nodeCount: 1
  config:
    apm-server.rum.enabled: true
  elasticsearchRef:
    name: textsearch-es